language: node_js
node_js:
- node
sudo: false
script:
- npm test
deploy:
  provider: heroku
  api_key:
    secure: KgFrPYmPwmYgzcheE5ckTimt3xi+1tVKUP6y8WOJVpfN13cj7UquiEFqWDjYJi6qejzgqOLktQea2gbCt0IvFylU/g3K7br3TNSSIZEmqH2352btB3qU1WBdNkeVhP0GMUeZq/lAaF0dEo28Q1p6Xkfzm8IscuNsVBla+eKT14VjmOIafGEfi+GpvsAC8aL6WTyxkY7Kz1q/CcBAIkrGC9PcNHykVCb+ZPT1KY6Gy2jGImdoIbt7Q6vM0F0X3iAwqsF3s9C7y7RVRWkLLBELGid/6S1dFCcAOpF/llkodV45hhmx/3RujDwff4bQ4/KahKX96OVKD1a75uRYSIFkra5y8JSecOvY8mggjrOlYw2kgwP3nyC/8H5+zhsZK4xwP44sWD9wHUp+XgYxa6nsUo7xG4tQhuH2ZpvDYTS6cBmeuajwfor1XKc61pG+sJ3rIZzo4jYA0RAoftsx14QqHhBFlROtsoFJindrLaBUawLF1imuk58mLd6hGaJ9MTPltgpX+SF3NCz2JWcLTaNRKXNrwtzZ6WlfP+IsmpoPwHVMMeLwfva65biMSoGOLdkOqnGZ6iH4sHEZOAxr5T6FO6ZDjlWskfTP2W9ckAtYqmtVDcNzUrZAGSiYH0Nlh3ebL5ryNUnygCdzRQGf1Ab+FG4BgVddgkRTKEKYYlQL6KE=
  app: appsecdidi
  edge: true
