language: node_js
node_js:
- node
sudo: false
script:
- npm test
deploy:
  provider: heroku
  api_key:
    secure: CqRI/lCjd0qNeAgzjKyJVClM6mezY2qubVcGsk5pYVaEy1CPDUGbeN72e8aa5bb+/UuY1I8BV0fV/hQu2n09QKLyaDV41ahlJdlHIbQtBePbGjBwLs2GbrblK91IDpl5Nj3HzabjgvxJHjjofA9GGE83+v/YxQFmLGc6fTYXdAqr1IrBktrOwrFv2Fq06lBSW6nWrYxscDsc+EzcsKBMjkHWo054Evfg7qgwM4EkHIddVxX1M0JoTmvfzFZ3RN47e22tQb/69RaUL5XhUOkjM9jfEBbfi2KpcvCRie6qZQFDmkKWRFyWyE99qj5bI4jJ8pQKdsRMhstEWZADpKJGHlscueiLkv9/FW3bn347C5yzycoUrrGZGk9phPWYztPBzTU2iIaODSRS8i6icnt9xFT/ULnYwJz/9jwk0/NBO7LFMbJv2M3GiQco6WlvbIKDuF1M1ZVpqdOByclZIguy6cgYoHPhI52C9dq1+bfp3PgrpH+F7FzRIrsdjZ0jhVtdOgPFK1IxXbk/ypckpM6emA3uGZzCZkHqa62GW2XUYWvfFERaSMk1PLIRT7ZAuHbvMY5QC5m9gf2kMhe/Nt9HuJTQ0LQlm5S43M+ZTrET/gyroyImjqtfWHhEO0ryxrkXdQohJFfh0SYYviuTC3Bjfu0lPRdHc5oVzvUo6U2x9Ds=
  app: appsecdidi
  edge: true
